//go:build amd64

// autogenerated - DO NOT EDIT!
// regenerate from the project root with:
// go run tools/gen-pcie-testdata/main.go --func makeXeonGold6230RFixture --pkg device --build-tag amd64

package device

import (
	"testing/fstest"
)

func makeXeonGold6230RFixture() fstest.MapFS {
	return fstest.MapFS{
		"devices/pci0000:00/pci_bus/0000:00/cpulistaffinity": &fstest.MapFile{
			Data: []byte("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102\n"),
		},
		"devices/pci0000:17/pci_bus/0000:17/cpulistaffinity": &fstest.MapFile{
			Data: []byte("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102\n"),
		},
		"devices/pci0000:3a/pci_bus/0000:3a/cpulistaffinity": &fstest.MapFile{
			Data: []byte("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102\n"),
		},
		"devices/pci0000:5d/pci_bus/0000:5d/cpulistaffinity": &fstest.MapFile{
			Data: []byte("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102\n"),
		},
		"devices/pci0000:80/pci_bus/0000:80/cpulistaffinity": &fstest.MapFile{
			Data: []byte("1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103\n"),
		},
		"devices/pci0000:85/pci_bus/0000:85/cpulistaffinity": &fstest.MapFile{
			Data: []byte("1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103\n"),
		},
		"devices/pci0000:ae/pci_bus/0000:ae/cpulistaffinity": &fstest.MapFile{
			Data: []byte("1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103\n"),
		},
		"devices/pci0000:d7/pci_bus/0000:d7/cpulistaffinity": &fstest.MapFile{
			Data: []byte("1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103\n"),
		},
		"devices/system/cpu/online": &fstest.MapFile{
			Data: []byte("0-103\n"),
		},
	}
}
