//go:build amd64

// autogenerated - DO NOT EDIT!
// regenerate from the project root with:
// go run tools/gen-pcie-testdata/main.go --func makeRyzen95950XFixture --pkg device --build-tag amd64

package device

import (
	"io/fs"
	"testing/fstest"
)

func makeRyzen95950XFixture() fstest.MapFS {
	return fstest.MapFS{
		"bus/pci/devices/0000:00:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:00.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:00.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:01.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:01.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:01.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:02.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:02.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:03.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:03.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:03.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:03.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:04.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:04.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:05.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:05.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:07.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:07.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:08.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:08.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:14.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:14.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:14.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:14.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.4": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.4"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.5": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.5"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.6": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.6"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:18.7": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:18.7"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:01:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.1/0000:01:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:20:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:03.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:04.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:05.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:08.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:09.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:21:0a.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:22:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/0000:22:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:25:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/0000:25:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:26:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/0000:26:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:27:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/0000:27:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2a:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2a:00.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2a:00.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2b:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/0000:2b:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2c:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/0000:2c:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2d:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:03.1/0000:2d:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2d:00.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:03.1/0000:2d:00.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2e:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.1/0000:2e:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2f:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.1/0000:2f:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2f:00.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.1/0000:2f:00.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:2f:00.4": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.1/0000:2f:00.4"),
			Mode: fs.ModeSymlink,
		},
		"devices/pci0000:00/0000:00:00.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:00.2/class": &fstest.MapFile{
			Data: []byte("0x080600\n"),
		},
		"devices/pci0000:00/0000:00:00.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:00.2/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:01.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.1/0000:01:00.0/class": &fstest.MapFile{
			Data: []byte("0x010802\n"),
		},
		"devices/pci0000:00/0000:00:01.1/0000:01:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.1/0000:01:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.1/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/0000:22:00.0/class": &fstest.MapFile{
			Data: []byte("0x010802\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/0000:22:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/0000:22:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/0000:25:00.0/class": &fstest.MapFile{
			Data: []byte("0x020000\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/0000:25:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/0000:25:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:03.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/0000:26:00.0/class": &fstest.MapFile{
			Data: []byte("0x010601\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/0000:26:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/0000:26:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:04.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/0000:27:00.0/class": &fstest.MapFile{
			Data: []byte("0x020000\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/0000:27:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/0000:27:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:05.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.0/class": &fstest.MapFile{
			Data: []byte("0x130000\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.3/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.3/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/0000:2b:00.0/class": &fstest.MapFile{
			Data: []byte("0x010601\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/0000:2b:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/0000:2b:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:09.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/0000:2c:00.0/class": &fstest.MapFile{
			Data: []byte("0x010601\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/0000:2c:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/0000:2c:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:0a.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/0000:20:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:01.2/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:01.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:01.2/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:02.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:02.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:02.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:03.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:03.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:03.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.0/class": &fstest.MapFile{
			Data: []byte("0x030000\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.1/class": &fstest.MapFile{
			Data: []byte("0x040300\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:03.1/0000:2d:00.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:03.1/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:03.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:03.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:04.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:04.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:04.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:05.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:05.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:05.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:07.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:07.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:07.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:07.1/0000:2e:00.0/class": &fstest.MapFile{
			Data: []byte("0x130000\n"),
		},
		"devices/pci0000:00/0000:00:07.1/0000:2e:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:07.1/0000:2e:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:07.1/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:07.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:08.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:08.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:08.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.0/class": &fstest.MapFile{
			Data: []byte("0x130000\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.3/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.3/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.4/class": &fstest.MapFile{
			Data: []byte("0x040300\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.4/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:08.1/0000:2f:00.4/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:08.1/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:08.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:08.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:14.0/class": &fstest.MapFile{
			Data: []byte("0x0c0500\n"),
		},
		"devices/pci0000:00/0000:00:14.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:14.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:14.3/class": &fstest.MapFile{
			Data: []byte("0x060100\n"),
		},
		"devices/pci0000:00/0000:00:14.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:14.3/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.0/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.1/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.1/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.2/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.2/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.3/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.3/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.4/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.4/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.4/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.5/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.5/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.5/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.6/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.6/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.6/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
		"devices/pci0000:00/0000:00:18.7/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:18.7/local_cpulist": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/pci0000:00/0000:00:18.7/numa_node": &fstest.MapFile{
			Data: []byte("-1\n"),
		},
	}
}
