// autogenerated - DO NOT EDIT!
package device

import (
	"io/fs"
	"testing/fstest"
)

func makeBasePCSysFSFixture() fstest.MapFS {
	return fstest.MapFS{
		"bus/pci/devices/0000:00:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:02.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:02.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:04.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:04.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:06.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:06.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:07.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:07.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:08.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:08.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:0d.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:0d.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:0d.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:0d.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:0d.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:0d.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:14.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:14.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:14.2": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:14.2"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:14.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:14.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:15.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:15.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:15.1": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:15.1"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:16.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:16.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:16.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:16.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:1f.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:1f.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:1f.3": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:1f.3"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:1f.4": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:1f.4"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:1f.5": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:1f.5"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:00:1f.6": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:1f.6"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:04:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:06.0/0000:04:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:50:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.2/0000:50:00.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:51:02.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:51:04.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:04.0"),
			Mode: fs.ModeSymlink,
		},
		"bus/pci/devices/0000:52:00.0": &fstest.MapFile{
			Data: []byte("../../../devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0/0000:52:00.0"),
			Mode: fs.ModeSymlink,
		},
		"devices/pci0000:00/0000:00:00.0/class": &fstest.MapFile{
			Data: []byte("0x060000\n"),
		},
		"devices/pci0000:00/0000:00:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:02.0/class": &fstest.MapFile{
			Data: []byte("0x030000\n"),
		},
		"devices/pci0000:00/0000:00:02.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:04.0/class": &fstest.MapFile{
			Data: []byte("0x118000\n"),
		},
		"devices/pci0000:00/0000:00:04.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:06.0/0000:04:00.0/class": &fstest.MapFile{
			Data: []byte("0x010802\n"),
		},
		"devices/pci0000:00/0000:00:06.0/0000:04:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:06.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:06.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0/0000:52:00.0/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0/0000:52:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:02.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:04.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/0000:51:04.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.2/0000:50:00.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:07.2/class": &fstest.MapFile{
			Data: []byte("0x060400\n"),
		},
		"devices/pci0000:00/0000:00:07.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:08.0/class": &fstest.MapFile{
			Data: []byte("0x088000\n"),
		},
		"devices/pci0000:00/0000:00:08.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:0d.0/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:0d.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:0d.2/class": &fstest.MapFile{
			Data: []byte("0x0c0340\n"),
		},
		"devices/pci0000:00/0000:00:0d.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:0d.3/class": &fstest.MapFile{
			Data: []byte("0x0c0340\n"),
		},
		"devices/pci0000:00/0000:00:0d.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:14.0/class": &fstest.MapFile{
			Data: []byte("0x0c0330\n"),
		},
		"devices/pci0000:00/0000:00:14.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:14.2/class": &fstest.MapFile{
			Data: []byte("0x050000\n"),
		},
		"devices/pci0000:00/0000:00:14.2/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:14.3/class": &fstest.MapFile{
			Data: []byte("0x028000\n"),
		},
		"devices/pci0000:00/0000:00:14.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:15.0/class": &fstest.MapFile{
			Data: []byte("0x0c8000\n"),
		},
		"devices/pci0000:00/0000:00:15.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:15.1/class": &fstest.MapFile{
			Data: []byte("0x0c8000\n"),
		},
		"devices/pci0000:00/0000:00:15.1/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:16.0/class": &fstest.MapFile{
			Data: []byte("0x078000\n"),
		},
		"devices/pci0000:00/0000:00:16.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:16.3/class": &fstest.MapFile{
			Data: []byte("0x070002\n"),
		},
		"devices/pci0000:00/0000:00:16.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:1f.0/class": &fstest.MapFile{
			Data: []byte("0x060100\n"),
		},
		"devices/pci0000:00/0000:00:1f.0/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:1f.3/class": &fstest.MapFile{
			Data: []byte("0x040380\n"),
		},
		"devices/pci0000:00/0000:00:1f.3/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:1f.4/class": &fstest.MapFile{
			Data: []byte("0x0c0500\n"),
		},
		"devices/pci0000:00/0000:00:1f.4/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:1f.5/class": &fstest.MapFile{
			Data: []byte("0x0c8000\n"),
		},
		"devices/pci0000:00/0000:00:1f.5/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/pci0000:00/0000:00:1f.6/class": &fstest.MapFile{
			Data: []byte("0x020000\n"),
		},
		"devices/pci0000:00/0000:00:1f.6/local_cpulist": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
		"devices/system/cpu/online": &fstest.MapFile{
			Data: []byte("0-7\n"),
		},
	}
}
