//go:build amd64

// autogenerated - DO NOT EDIT!
// regenerate from the project root with:
// go run tools/gen-pcie-testdata/main.go --func makeRyzen95950XFixture --pkg device --build-tag amd64

package device

import (
	"testing/fstest"
)

func makeRyzen95950XFixture() fstest.MapFS {
	return fstest.MapFS{
		"devices/pci0000:00/pci_bus/0000:00/cpulistaffinity": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
		"devices/system/cpu/online": &fstest.MapFile{
			Data: []byte("0-31\n"),
		},
	}
}
