# See https://cloud.google.com/cloud-build/docs/build-config

options:
  substitutionOption: ALLOW_LOOSE
steps:
  - name: registry.k8s.io/releng/gcb-docker-gcloud:v20260806
    entrypoint: ./scripts/build-and-publish-image.sh
    env:
    - IMG_PREFIX=us-central1-docker.pkg.dev/k8s-staging-images/dra-driver-cpu
    - IMG_TAG=$TAG_NAME
