# This example illustrates a Pod consuming exclusive CPUs under Grouped CPU Device Mode (default).
#
# Required Driver Configuration:
#   --cpu-device-mode: "grouped" (CPUs are grouped, e.g. by NUMA node, and exposed as consumable capacity).
#   --disable-node-allocatable-mapping: true (Required because container CPU requests are explicitly replicated in
#                                            the standard 'resources.requests.cpu' block to perform manual scheduling
#                                            accounting and prevent scheduler-level double-counting).
#
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: claim-cpu-capacity-10
spec:
  devices:
    requests:
    - name: req-cpu-slice
      exactly:
        deviceClassName: dra.cpu
        capacity:
          requests:
            dra.cpu/cpu: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cpu-dra-claim
spec:
  containers:
    - name: workload-container
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "10"
        limits:
          cpu: "10"
        claims:
          - name: "pod-cpu-claim-ref"
  resourceClaims:
    - name: "pod-cpu-claim-ref"
      resourceClaimName: claim-cpu-capacity-10
