/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package driverconfig

import (
	"encoding/json"
	"fmt"
	"slices"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/kubernetes-sigs/dra-driver-cpu/pkg/device"
)

// schemaExcludedFields maps Config json keys not settable via the config
// file to the alternative a user should use instead. They're removed from
// the generated schema and rejected by Load if present in a config file.
var schemaExcludedFields = map[string]string{
	"bindAddress":     "use helm chart's healthzPort instead",
	"exposePCIeRoots": "use args.exposePCIeRoots instead",
	"kubeletRootDir":  "use the chart's top-level kubeletRootDir value, or --kubelet-root-dir when running the binary directly",
}

// schemaEnums are the allowed values for fields whose Go type (string) can't
// express them on its own.
var schemaEnums = map[string][]any{
	"cpuDeviceMode": {device.CPU_DEVICE_MODE_GROUPED, device.CPU_DEVICE_MODE_INDIVIDUAL},
	"groupBy":       {device.GROUP_BY_NUMA_NODE, device.GROUP_BY_SOCKET, device.GROUP_BY_MACHINE},
}

// driverConfigSchemaComment is the generated schema's top-level "$comment".
const driverConfigSchemaComment = "Schema for driverConfig values. Mirrors internal/driverconfig/config.go Config struct, except bindAddress, exposePCIeRoots, and kubeletRootDir, which are rejected in the config file — use healthzPort, args.exposePCIeRoots, and either the chart's top-level kubeletRootDir value or --kubelet-root-dir for direct binary use. Generated by 'make driverconfig-schema'; do not edit by hand."

// GenerateDriverConfigSchema builds the driver config JSON Schema from
// Config, applying schemaExcludedFields and schemaEnums.
func GenerateDriverConfigSchema() ([]byte, error) {
	schema, err := jsonschema.For[Config](nil)
	if err != nil {
		return nil, fmt.Errorf("inferring schema from Config: %w", err)
	}

	for jsonKey := range schemaExcludedFields {
		if _, ok := schema.Properties[jsonKey]; !ok {
			return nil, fmt.Errorf("schemaExcludedFields has entry %q but Config has no matching field", jsonKey)
		}
		delete(schema.Properties, jsonKey)
		schema.Required = slices.DeleteFunc(schema.Required, func(k string) bool { return k == jsonKey })
	}

	for jsonKey, enum := range schemaEnums {
		prop, ok := schema.Properties[jsonKey]
		if !ok {
			return nil, fmt.Errorf("schemaEnums has entry %q but Config has no matching field", jsonKey)
		}
		prop.Enum = enum
	}

	schema.Properties["apiVersion"] = &jsonschema.Schema{
		Type: "string",
		Enum: []any{ConfigAPIVersion},
	}
	schema.PropertyOrder = append([]string{"apiVersion"}, schema.PropertyOrder...)

	schema.Schema = "https://json-schema.org/draft/2020-12/schema"
	schema.ID = "driverconfig.schema.json"
	schema.Comment = driverConfigSchemaComment

	out, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshaling schema: %w", err)
	}
	return append(out, '\n'), nil
}
