package main

import (
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/kubernetes-sigs/dra-driver-cpu/pkg/device"
	"k8s.io/klog/v2"
)

func main() {
	sysfsRoot := device.SysfsRoot
	flag.StringVar(&sysfsRoot, "sysfs-root", sysfsRoot, "sysfs root path")
	klog.InitFlags(nil)
	flag.Parse()

	sysfs := os.DirFS(sysfsRoot).(device.SysFS)

	var err error
	args := flag.Args()
	if len(args) == 0 {
		err = runScan(sysfs)
	} else {
		switch args[0] {
		case "scan-pci":
			err = runScan(sysfs)
		case "dump-mapfs":
			err = runDumpMapFS(sysfs, args[1:])
		default:
			err = fmt.Errorf("unknown subcommand: %s", args[0])
		}
	}
	if err != nil {
		klog.Fatalf("%v", err)
	}
}

func runScan(sysfs device.SysFS) error {
	domains, err := device.PCIEDomainsFromFS(sysfs)
	if err != nil {
		return fmt.Errorf("failed to scan the PCIE domains: %w", err)
	}

	klog.V(3).Infof("found %d PCIE domains", len(domains))
	for _, dom := range domains {
		klog.Infof("PCIE domain: %s", dom.String())
	}

	onlineCPUs, err := device.OnlineCPUs(sysfs)
	if err != nil {
		return fmt.Errorf("failed to get the online CPUs: %w", err)
	}

	orphans := device.FindOrphanedCPUs(domains, onlineCPUs)
	klog.V(3).Infof("found %d orphaned CPUs", orphans.Size())
	return nil
}

type mapFSEntry struct {
	Path   string
	Data   []byte
	IsLink bool
}

func (fse mapFSEntry) Emit(w io.Writer) {
	fmt.Fprintf(w, "%q: &fstest.MapFile{\n", fse.Path)
	fmt.Fprintf(w, "\tData: []byte(%q),\n", string(fse.Data))
	if fse.IsLink {
		fmt.Fprintln(w, "\tMode: fs.ModeSymlink,")
	}
	fmt.Fprintln(w, "},")
}

type mapFSGen struct {
	Func    string
	Pkg     string
	entries []mapFSEntry
}

func (gen *mapFSGen) SetDefaults() {
	gen.Func = "makeSysfsFixture"
	gen.Pkg = "device"
}

func (gen *mapFSGen) Reset() {
	gen.entries = nil
}

func runDumpMapFS(sysfs device.SysFS, args []string) error {
	gen := &mapFSGen{}
	gen.SetDefaults()
	fs := flag.NewFlagSet("dump-mapfs", flag.PanicOnError)
	fs.StringVar(&gen.Func, "func", gen.Func, "function name for the generated MapFS fixture")
	fs.StringVar(&gen.Pkg, "pkg", gen.Pkg, "package name for the generated MapFS fixture")
	_ = fs.Parse(args)

	gen.Reset()
	err := gen.CollectFromSysfs(sysfs)
	if err != nil {
		return fmt.Errorf("failed to collect sysfs snapshot: %w", err)
	}
	src, err := gen.MapFSSource()
	if err != nil {
		return fmt.Errorf("failed to generate MapFS source: %w", err)
	}
	fmt.Print(string(src))
	return nil
}

func (gen *mapFSGen) ReadDataFrom(sysfs device.SysFS, sysPath string) error {
	data, err := fs.ReadFile(sysfs, sysPath)
	if err != nil {
		return fmt.Errorf("reading data %q: %w", sysPath, err)
	}
	gen.entries = append(gen.entries, mapFSEntry{
		Path: sysPath,
		Data: data,
	})
	return nil
}

func (gen *mapFSGen) ReadLinkFrom(sysfs device.SysFS, sysPath string) (string, error) {
	target, err := fs.ReadLink(sysfs, sysPath)
	if err != nil {
		return "", fmt.Errorf("reading link %q: %w", sysPath, err)
	}
	gen.entries = append(gen.entries, mapFSEntry{
		Path:   sysPath,
		Data:   []byte(target),
		IsLink: true,
	})
	return target, nil
}

func (gen *mapFSGen) Emit(w io.Writer) {
	fmt.Fprintf(w, "return fstest.MapFS{\n")
	for _, entry := range gen.entries {
		entry.Emit(w)
	}
	fmt.Fprintf(w, "}\n")
}

func (gen *mapFSGen) CollectFromSysfs(sysfs device.SysFS) error {
	err := gen.ReadDataFrom(sysfs, filepath.Join("devices", "system", "cpu", "online"))
	if err != nil {
		return err
	}
	err = device.ScanPCIDevices(sysfs, func(pciDev device.PCIEDevice) error {
		// entry point link in bus/pci/devices
		target, err := gen.ReadLinkFrom(sysfs, pciDev.SysfsPath())
		if err != nil {
			return err
		}
		// resolve the link and fetch the real content to sit in devices/pciDOMAIN/...
		devicePath := filepath.Clean(filepath.Join(pciDev.BaseDirPath(), target))
		err = gen.ReadDataFrom(sysfs, filepath.Join(devicePath, "class"))
		if err != nil {
			return err
		}
		err = gen.ReadDataFrom(sysfs, filepath.Join(devicePath, "local_cpulist"))
		if err != nil {
			return err
		}
		return nil
	})
	sort.SliceStable(gen.entries, func(i, j int) bool {
		return gen.entries[i].Path < gen.entries[j].Path
	})
	return err
}

func (gen *mapFSGen) MapFSSource() ([]byte, error) {
	preambleText := `
// autogenerated - DO NOT EDIT!
package {{.Pkg}}

import (
    "io/fs"
    "testing/fstest"
)

func {{.Func}}() fstest.MapFS {
`
	var sb strings.Builder
	preamble, err := template.New("preamble").Parse(preambleText)
	if err != nil {
		return nil, err
	}
	if err := preamble.Execute(&sb, gen); err != nil {
		return nil, err
	}
	gen.Emit(&sb)
	fmt.Fprintf(&sb, "}\n") // func end
	return format.Source([]byte(sb.String()))
}
