/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"

	"github.com/go-logr/logr"
	"github.com/go-logr/stdr"
	"github.com/kubernetes-sigs/dra-driver-cpu/pkg/device"
)

const (
	defaultFuncName = "makeSysfsFixture"
	defaultPkgName  = "device"
)

func main() {
	sysfsRoot := device.SysfsRoot
	gen := newMapFSGen()

	flag.StringVar(&sysfsRoot, "sysfs-root", sysfsRoot, "sysfs root path")
	flag.StringVar(&gen.BuildTag, "build-tag", gen.BuildTag, "inject a //go:build constraint for the current architecture, set \"\" to disable")
	flag.StringVar(&gen.Func, "func", gen.Func, "function name for the generated MapFS fixture")
	flag.StringVar(&gen.Pkg, "pkg", gen.Pkg, "package name for the generated MapFS fixture")
	flag.Parse()

	if gen.Func == defaultFuncName {
		if model := detectCPUModel(); model != "" {
			gen.Func = "make" + model + "Fixture"
		}
	}

	sysfs := os.DirFS(sysfsRoot).(device.SysFS)
	logger := stdr.New(log.Default())

	// need to silence output on the happy path so we can
	// trivially redirect the output to a file
	err := gen.Collect(logr.Discard(), sysfs)
	if err != nil {
		logger.Error(err, "failed to collect sysfs snapshot")
		os.Exit(2)
	}
	src, err := gen.Generate()
	if err != nil {
		logger.Error(err, "failed to generate MapFS source")
		os.Exit(4)
	}
	fmt.Print(string(src))
}

type mapFSEntry struct {
	Path string
	Data []byte
}

func (fse mapFSEntry) Emit(w io.Writer) {
	fmt.Fprintf(w, "%q: &fstest.MapFile{\n", fse.Path)
	fmt.Fprintf(w, "\tData: []byte(%q),\n", string(fse.Data))
	fmt.Fprintln(w, "},")
}

type mapFSGen struct {
	Func     string
	Pkg      string
	BuildTag string
	entries  []mapFSEntry
}

func newMapFSGen() *mapFSGen {
	return &mapFSGen{
		Func:     defaultFuncName,
		Pkg:      defaultPkgName,
		BuildTag: runtime.GOARCH,
	}
}

func (gen *mapFSGen) ReadDataFrom(sysfs device.SysFS, sysPath string) error {
	data, err := fs.ReadFile(sysfs, sysPath)
	if err != nil {
		return fmt.Errorf("reading data %q: %w", sysPath, err)
	}
	gen.entries = append(gen.entries, mapFSEntry{
		Path: sysPath,
		Data: data,
	})
	return nil
}

func (gen *mapFSGen) Emit(w io.Writer) {
	fmt.Fprintf(w, "return fstest.MapFS{\n")
	for _, entry := range gen.entries {
		entry.Emit(w)
	}
	fmt.Fprintf(w, "}\n")
}

func (gen *mapFSGen) Collect(logger logr.Logger, sysfs device.SysFS) error {
	devicesDir := "devices"
	entries, err := fs.ReadDir(sysfs, devicesDir)
	if err != nil {
		return fmt.Errorf("reading %q: %w", devicesDir, err)
	}

	for _, entry := range entries {
		if !device.IsPCIeRootName(entry.Name()) {
			continue
		}
		busID := strings.TrimPrefix(entry.Name(), "pci")
		affinityPath := filepath.Join(devicesDir, entry.Name(), "pci_bus", busID, "cpulistaffinity")
		if err := gen.ReadDataFrom(sysfs, affinityPath); err != nil {
			return err
		}
		logger.Info("collected PCIe root", "root", entry.Name(), "path", affinityPath)
	}

	cpuOnlinePath := filepath.Join(devicesDir, "system", "cpu", "online")
	if err := gen.ReadDataFrom(sysfs, cpuOnlinePath); err != nil {
		return err
	}

	sort.SliceStable(gen.entries, func(i, j int) bool {
		return gen.entries[i].Path < gen.entries[j].Path
	})
	return nil
}

func (gen *mapFSGen) Generate() ([]byte, error) {
	preambleText := `
{{- if .BuildTag}}
//go:build {{.BuildTag}}

{{end -}}
// autogenerated - DO NOT EDIT!
// regenerate from the project root with:
// go run tools/gen-pcie-testdata/main.go --func {{.Func}} --pkg {{.Pkg}}{{if .BuildTag}} --build-tag {{.BuildTag}}{{end}}

package {{.Pkg}}

import (
    "testing/fstest"
)

func {{.Func}}() fstest.MapFS {
`
	var sb strings.Builder
	preamble, err := template.New("preamble").Parse(preambleText)
	if err != nil {
		return nil, err
	}
	if err := preamble.Execute(&sb, gen); err != nil {
		return nil, err
	}
	gen.Emit(&sb)
	fmt.Fprintf(&sb, "}\n") // func end
	return format.Source([]byte(sb.String()))
}

// detectCPUModel reads the CPU model name from /proc/cpuinfo and
// sanitizes it into a CamelCase Go identifier fragment.
// Returns empty string if detection fails.
func detectCPUModel() string {
	data, err := os.ReadFile("/proc/cpuinfo")
	if err != nil {
		return ""
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		name, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		if strings.TrimSpace(name) != "model name" {
			continue
		}
		return sanitizeModelName(strings.TrimSpace(value))
	}
	return ""
}

// sanitizeModelName keeps only alphanumeric characters from the model string.
func sanitizeModelName(model string) string {
	var sb strings.Builder
	for _, c := range model {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			sb.WriteRune(c)
		}
	}
	return sb.String()
}
